### PR TITLE
(5P) Run PHPCS on push only

### PR DESCRIPTION
**Pull request by obenland**
Running it on `push` and `pull_request` led to duplicate checks.

### CODE REVIEW

**Comment by getdave** [comment]
@obenland Can you advise how we can set this up to run locally in our editors on "Save"? I think I got it working once but I've forgotten...

**Review by getdave — COMMENTED** [review]
This looks good from what I can tell. I'm not very familiar with how this all works so would value a run through of this when you have time.

**Comment by obenland** [comment]
> @obenland Can you advise how we can set this up to run locally in our editors on "Save"? I think I got it working once but I've forgotten...

Yeah, so I have phpcs installed through Homebrew, but you can also just follow the instructions here: https://github.com/squizlabs/PHP_CodeSniffer#installation. I then followed the wpcs installation instructions to add the WordPress standard: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards#standalone

Specifically: In `/usr/local/etc/` I checked out the repo into a `wpcs` folder (as outlined in their instructions, and then added that path to phpcs' install path:
```
$ phpcs --config-set installed_paths /usr/local/etc/wpcs/
```

In PHPStorm I enabled their built-in integration (not sure if it requires a plugin):
image

**Review by marekhrabe — APPROVED** [review]
Anything blocking this merge at this point? It's mainly for the github workflow setup as I understand it and we can add more docs on local setup later.

**Comment by mrrobot47** [comment]
Just a suggestion, you should keep the GitHub action `rtCamp/action-phpcs-code-review` to run on `pull_request` and not on `push`.

### Reasons
1. `pull_request` event includes trigger of event when a PR is created, as well as syncronization trigger, i.e., whenever a new commit is added to the PR.
2. If `push` event trigger is setup then there is possibility of falsely skipping a review when PR is created. 
Example scenario that will cause issue:
* a branch `feature-1` is created
* One/many new commit(s) is/are pushed to it, this will trigger phpcs review action run as `push` event trigger is setup. But the action run will skip scanning these files as they are not a part of PR.
* Work get's completed on branch `feature-1` and a PR is created, but now there will be no comments coming up on it, as `push` event does trigger action run on PR creation. Hence, code with phpcs errors will show a green tick mark and no actions run on that PR.
* Only when a commit is added to this branch after PR creation, that the PHPCS review action will be executed.

**Pull request merged**
